### ISSUE TITLE
Error occurred when executing GLIGEN_GUI: 'Response' object is not subscriptable

### ISSUE THREAD

**Issue by TheByXy** [mut-ex/comfyui-gligengui-node#1]
Hello! Found a bug:
Throws an error when trying to Queue Prompt (with GLIGEN GUI launched)
![image](https://github.com/mut-ex/comfyui-gligengui-node/assets/115401774/744ebb68-4df0-4a83-8e56-ee96ec2eea8f)
![image](https://github.com/mut-ex/comfyui-gligengui-node/assets/115401774/8eeb0248-fad8-4c8c-acbe-d7263a8cbb60)

**Comment by raphatbho** [comment]
Can confirm.

**Comment by Sonsaiy** [comment]
Me too.

**Comment by ZeTofZone** [comment]
Hi.

I have the same problem.

Seems to be resolved by uncomment the line 98 in the file : \gligen_gui\static\js\extras.js ==> ("postInputArgs();" which is actually a comment)

**Comment by Wraithnaut** [comment]
> Seems to be resolved by uncomment the line 98 in the file : \gligen_gui\static\js\extras.js ==> ("postInputArgs();" which is actually a comment)

Can confirm that file edit fixes the issue.

**Comment by TheByXy** [comment]
> Seems to be resolved by uncomment the line 98 in the file : \gligen_gui\static\js\extras.js ==> ("postInputArgs();" which is actually a comment)

Agree, it is working now, thank you!
Do I need to close the issue now? Or leave this open until mut-ex's fixing this in code?

**Comment by hjcxlp** [comment]
> > Seems to be resolved by uncomment the line 98 in the file : \gligen_gui\static\js\extras.js ==> ("postInputArgs();" which is actually a comment)
> 
> Agree, it is working now, thank you! Do I need to close the issue now? Or leave this open until mut-ex's fixing this in code?

pls confirm if changes are made as follow:
  saveToLocalStorage() {
  ("postInputArgs();" 
    localStorage.setItem("globalState", this.stringify());
  }

**Comment by aflyrt** [comment]
```
got prompt
!!! Exception during processing!!! 'Response' object is not subscriptable
Traceback (most recent call last):
  File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-gligengui-node\__init__.py", line 72, in append
    boxes = res["boxes"]
            ~~~^^^^^^^^^
TypeError: 'Response' object is not subscriptable
```
